/*!
 * Project : simply-countdown
 * File : simplyCountdown
 * Date : 27/06/2015
 * License : MIT
 * Version : 1.3.2
 * Author : Vincent Loy <vincent.loy1@gmail.com>
 * Contributors : 
 *  - Justin Beasley <JustinB@harvest.org>
 *  - Nathan Smith <NathanS@harvest.org>
 */
/*global window, document*/
!function(a){"use strict";var b,c,d,e;b=function(a){var c,d,e;for(a=a||{},c=1;c<arguments.length;c+=1)if(d=arguments[c])for(e in d)d.hasOwnProperty(e)&&("object"==typeof d[e]?b(a[e],d[e]):a[e]=d[e]);return a},d=function(a,b,c){var d,e,f,g;return e=document.createElement("div"),f=document.createElement("span"),g=document.createElement("span"),d=document.createElement("div"),d.appendChild(f),d.appendChild(g),e.appendChild(d),e.classList.add(b.sectionClass),e.classList.add(c),f.classList.add(b.amountClass),g.classList.add(b.wordClass),a.appendChild(e),{full:e,amount:f,word:g}},c=function(a,b){var c;return a.inline?(c=document.createElement("span"),c.classList.add(a.inlineClass),c):{days:d(b,a,"simply-days-section"),hours:d(b,a,"simply-hours-section"),minutes:d(b,a,"simply-minutes-section"),seconds:d(b,a,"simply-seconds-section")}},e=function(a,d){var f,g,h,i,j,k,l,m,n,o,e=b({year:2015,month:6,day:28,hours:0,minutes:0,seconds:0,words:{days:"day",hours:"hour",minutes:"minute",seconds:"second",pluralLetter:"s"},plural:!0,inline:!1,enableUtc:!0,onEnd:function(){},refresh:1e3,inlineClass:"simply-countdown-inline",sectionClass:"simply-section",amountClass:"simply-amount",wordClass:"simply-word",zeroPad:!1},d),p=document.querySelectorAll(a);h=new Date(e.year,e.month-1,e.day,e.hours,e.minutes,e.seconds),g=e.enableUtc?new Date(h.getUTCFullYear(),h.getUTCMonth(),h.getUTCDate(),h.getUTCHours(),h.getUTCMinutes(),h.getUTCSeconds()):h,Array.prototype.forEach.call(p,function(a){var d,b=c(e,a);d=function(){var c,d,h,p;i=new Date,e.enableUtc?(j=new Date(i.getFullYear(),i.getMonth(),i.getDate(),i.getHours(),i.getMinutes(),i.getSeconds()),k=(g-j.getTime())/1e3):k=(g-i.getTime())/1e3,k>0?(l=parseInt(k/86400,10),k%=86400,m=parseInt(k/3600,10),k%=3600,n=parseInt(k/60,10),o=parseInt(k%60,10)):(l=0,m=0,n=0,o=0,window.clearInterval(f),e.onEnd()),e.plural?(c=l>1?e.words.days+e.words.pluralLetter:e.words.days,d=m>1?e.words.hours+e.words.pluralLetter:e.words.hours,h=n>1?e.words.minutes+e.words.pluralLetter:e.words.minutes,p=o>1?e.words.seconds+e.words.pluralLetter:e.words.seconds):(c=e.words.days,d=e.words.hours,h=e.words.minutes,p=e.words.seconds),e.inline?a.innerHTML=l+" "+c+", "+m+" "+d+", "+n+" "+h+", "+o+" "+p+".":(b.days.amount.textContent=(e.zeroPad&&l.toString().length<2?"0":"")+l,b.days.word.textContent=c,b.hours.amount.textContent=(e.zeroPad&&m.toString().length<2?"0":"")+m,b.hours.word.textContent=d,b.minutes.amount.textContent=(e.zeroPad&&n.toString().length<2?"0":"")+n,b.minutes.word.textContent=h,b.seconds.amount.textContent=(e.zeroPad&&o.toString().length<2?"0":"")+o,b.seconds.word.textContent=p)},d(),f=window.setInterval(d,e.refresh)})},a.simplyCountdown=e}(window),window.jQuery&&!function(a,b){"use strict";function c(a,c){b(a,c)}a.fn.simplyCountdown=function(a){return c(this.selector,a)}}(jQuery,simplyCountdown);